--Every command here will be executed when the container is created

CREATE TABLE USERS (
    USERID SERIAL PRIMARY KEY,
    USEREMAIL VARCHAR(255),
    USERNAME VARCHAR(255),
    USERPASSWORD VARCHAR(255),
    USERBIRD VARCHAR(255)
);

CREATE TABLE CATEGORIES (
    CODE SERIAL PRIMARY KEY,
    CATEGORIESNAME VARCHAR(255),
    TAX NUMERIC(10,2)
);

CREATE TABLE PRODUCTS (
    CODE SERIAL PRIMARY KEY,
    PRODUCTSNAME VARCHAR(255),
    PRICE NUMERIC(10,2),
    AMOUNT INTEGER,
    CATEGORY_CODE INTEGER,
    CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_CODE) REFERENCES CATEGORIES(CODE)
);

CREATE TABLE HISTORY (
    CODE SERIAL PRIMARY KEY,
    TOTAL NUMERIC(10,2),
    TAX NUMERIC(10,2),
    HUSERID INTEGER,
    CONSTRAINT FK_USER FOREIGN KEY (HUSERID) REFERENCES USERS(USERID)
);

CREATE TABLE DETAILS (
    CODE SERIAL PRIMARY KEY,
    HISTORY_CODE INTEGER,
    PRODUCT_CODE INTEGER,
    AMOUNT INTEGER,
    PRICE NUMERIC(10,2),
    TAX NUMERIC(10,2),
    CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCTS(CODE),
    CONSTRAINT FK_HISTORY FOREIGN KEY (HISTORY_CODE) REFERENCES HISTORY(CODE)
);

CREATE TABLE HOME (
    HOMEID SERIAL PRIMARY KEY,
    PRODUCT_CODE INTEGER,
    PRICE NUMERIC(10,2),
    HAMOUNT INTEGER,
    HTOTAL NUMERIC(10,2),
    CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCTS(CODE)
);
